version: '3'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./images/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./src:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - composer_cache_volume:/root/.composer/cache
    networks:
      - default_network

  webserver:
    container_name: webserver
    image: nginx:1.24.0
    ports:
      - 80:80
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    networks:
      - default_network

  db:
    container_name: db
    image: mariadb:10.6.13
    expose:
      - 3306
    volumes:
      - ./config/mariadb:/usr/local/etc/mysql/conf.d
      - db_data_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
      - default_network

  cache:
    container_name: cache
    image: redis:7.0.11
    expose:
      - 6379
    volumes: 
      - cache_volume
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - default_network
      
volumes:
  db_data_volume:
  composer_cache_volume:
  cache_volume:

networks:
  default_network:
    driver: bridge